server:
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/home
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  ldap:
    username: cn=admin,dc=urr4,dc=com
    password: ${LDAP_PASSWORD}
springdoc:
  api-docs:
    path: /open-api
