server:
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /open-api

org:
  neo4j:
    driver:
      uri: ${neo4j.url}
      authentication:
        username: ${neo4j.user}
        password: ${neo4j.password}
      config:
        encrypted: true
