name: Build and Push Docker Image CI

on:
  push:
    branches: [ hex ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
          ls
          ./distributeDockerImages.sh ${GITHUB_SHA}