name: Build and Push Docker Image CI

on:
  push:
    branches: [ hex ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Docker buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: "08021986"
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the Docker image
        run: |
          echo ${GITHUB_SHA}
          docker build --push --platform linux/arm/v7 -t 08021986/meal-planner-be:latest .